$(function(){
    $('.btn_gnb_open').click(function(){
        $('.gnb_wrap').addClass('on');
        $('.gnb_bg').fadeIn('on');
    })
    $('.btn_gnb_close').click(function(){
        $('.gnb_wrap').removeClass('on');
        $('.gnb_bg').fadeOut('on');
    })
    $('.gnb_bg').click(function(){
        $('.gnb_wrap').removeClass('on');
        $('.gnb_bg').fadeOut('on');
    })
})